config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :posts do
    resources :comments, only: :create
    collection do
      get :user_library
    end
  end
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  validates :content, presence: true
end

app/models/concerns/statusable.rb
# app/models/concerns/statusable.rb
module Statusable
  extend ActiveSupport::Concern

  included do
    enum status: { draft: 0, published: 1 }
    scope :published, -> { where(status: 'published') }
    scope :draft, -> { where(status: 'draft') }
  end
end

app/models/post.rb
class Post < ApplicationRecord
  include Statusable

  has_many :comments, as: :commentable, dependent: :destroy
  belongs_to :user
  has_one_attached :image
  has_one_attached :video

  validates :title, :content, :status, :author, presence: true

  before_create :set_creation_date
  before_save :set_published_date

  validate :video_content_type

  private

  def set_creation_date
    self.creation_date = Time.current
  end

  def set_published_date
    if status_changed? && status == "published"
      self.published_date = Time.current
    end
  end

  def video_content_type
    if video.attached? && !video.content_type.in?(%w(video/mp4))
      errors.add(:video, 'must be a valid MP4 file')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @commentable = find_commentable
    @comment = @commentable.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to @commentable, notice: "Comment posted successfully."
    else
      redirect_to @commentable, alert: "Error creating comment."
    end
  end

  private

  # This will the dynamic resource for comment build
  def find_commentable
    params.each do |name, value|
      if name =~ /(.+)_id$/
        return $1.classify.constantize.find(value)
      end
    end
    nil
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index show ]

  def index
    @posts = Post.published
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = current_user.posts.new(post_params)
    @post.author = current_user.email if user_signed_in?

    if @post.save
      redirect_to @post, notice: "Post was successfully created."
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: "Post was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    if @post.destroy
      redirect_to posts_url, notice: "Post was successfully deleted."
    else
      redirect_to posts_url, alert: "Something went wrong"
    end
  end

  def user_library
    @user_posts = current_user.posts
  end

  private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :content, :status, :author, :image, :video)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<div class="list-group-item list-group-item-action mb-2">
  <div class="d-flex w-100 justify-content-between">
    <h6 class="mb-1"><%= comment.user&.username %></h6>
    <small><%= comment.created_at.strftime("%B %d, %Y at %I:%M %p") %></small>
  </div>
  <p class="mb-1"><%= comment.content %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">BlogApp</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <a class="nav-link" href="#">Signed in as <%= current_user.email %></a>
              </li>
              <li class="nav-item">
                <%= button_to 'Logout', destroy_user_session_path,method: :delete, class: "nav-link logout-link" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Login', new_user_session_path, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <% if notice || alert %>
      <div class="mt-2 alert alert-<%= notice && "success" || alert && "danger" %>" role="alert" id="notice">
        <%= notice %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <div class="form-group">
      <%= form.label :title, class: "form-label" %>
      <%= form.text_field :title, class: "form-control" %>
    </div>
  </div>

  <div class="mb-3">
    <div class="form-group">
      <%= form.label :content, class: "form-label" %>
      <%= form.text_area :content, class: "form-control" %>
    </div>
  </div>

  <div class="mb-3">
    <div class="form-group">
      <%= form.label :status, class: "form-label" %>
      <%= form.select :status, options_for_select([['Draft', 'draft'], ['Published', 'published']], post.status), {}, class: "form-control" %>
    </div>
  </div>

  <div class="mb-3">
    <div class="form-group">
      <%= form.label :image, class: "form-label" %>
      <%= form.file_field :image, class: "form-control" %>
    </div>
  </div>

  <div class="mb-3">
    <div class="form-group">
      <%= form.label :video, class: "form-label" %>
      <%= form.file_field :video, class: "form-control", accept: 'video/mp4' %>
    </div>
  </div>

  <div class="form-group">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="col-md-3 me-4 mb-4 shadow p-3 mb-5 bg-body rounded">
  <%= link_to post_path(post) do %>
    <div class="card">
      <% if post.image.attached? %>
        <%= image_tag post.image, class: "card-img-top", alt: "post_image"%>
      <% else %>
        <%= image_tag "blog_default.png", class: "card-img-top", alt: "default_image"%>
      <% end %>
      <div class="card-body">
        <h5 class="card-title"><%= link_to post.title, post %></h5>
        <p class="card-text"><strong>Author:</strong> <%= post.user.username %></p>
        <p class="card-text"><strong>Published on:</strong> <%= post.published_date&.strftime("%B %d, %y") %></p>
        <p class="card-text"><%= truncate(post.content, length: 100) %></p>
        <div class="d-flex justify-content-between">
          <%= link_to 'Read more', post, class: 'btn btn-primary' %>
          <% if user_signed_in? && current_user.email == post.author %>
            <%= link_to 'Edit', edit_post_path(post), class: 'btn btn-primary' %>
          <% end %>
        </div>
      </div>
    </div>
 <% end %>
</div>

app/views/posts/edit.html.erb
<h1 class="text-center mt-4">Edit post</h1>
<div class="container">
  <%= render "form", post: @post %>
  <div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>
</div>
<br>

app/views/posts/index.html.erb
<% if user_signed_in? %>
  <div class="text-end m-4">
    <%= link_to 'New Post', new_post_path, class: 'btn btn-primary' %>
    <%= link_to 'My library', user_library_posts_path, class: 'btn btn-primary' %>
  </div>
<% end %>
<div class="container-fluid ms-5">
  <% if @posts.empty? %>
    <div class="text-center mt-5">
      <h3>Feed doesn't have any posts yet</h3>
    </div>
  <% else %>
    <div class="row">
      <%= render partial: 'post', collection: @posts %>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="container mt-4">
  <%= render "form", post: @post %>
  <div>
    <%= link_to "Back to posts", posts_path %>
  </div>
</div>
<br>

app/views/posts/show.html.erb
<div class="container mt-4">
  <div class="card mb-4">
    <div class="card-body">
      <h3 class="card-title"><%= @post.title %></h3>
      <p class="card-text"><b>Content:</b> <%= @post.content %></p>
      <p class="card-text"><b>Author:</b> <%= @post.user.username %></p>
      <% if @post.published_date %>
       <p class="card-text"><b>Published on:</b> <%= @post.published_date&.strftime("%B %d, %Y") %></p>
       <% end %>
    </div>
    <% if @post.image.attached? %>
      <img src="<%= url_for(@post.image) %>" class="card-img-bottom img-fluid" alt="Post image">
    <% end %>
    <% if @post.video.attached? %>
      <div class="card-footer">
        <h2>Videos</h2>
        <%= video_tag url_for(@post.video), controls: true, class: "video-fluid w-100" %>
      </div>
    <% end %>
  </div>

  <h4>Comments</h4>
  <div class="list-group mb-4">
    <%= render partial: "comments/comment", collection: @post.comments %>
  </div>

  <% if user_signed_in? %>
    <h4>Add a comment:</h4>
    <%= form_with(model: [@post, @post.comments.build], local: true, class: "mb-4") do |form| %>
      <div class="mb-3">
        <div class="form-group">
          <%= form.text_area :content, class: "form-control", placeholder: "Write comment" %>
        </div>
      </div>
      <div class="form-group">
        <%= form.submit "Add Comment", class: "btn btn-primary" %>
      </div>
      <div>
        <%= link_to "Back to posts", posts_path %>
      </div>
    <% end %>
  <% else %>
    <p><%= link_to "Log in to add a comment", new_user_session_path, class: "btn btn-primary" %></p>
  <% end %>
</div>

app/views/posts/user_library.html.erb
<div class="container mt-4">
  <h1>Your Posts</h1>
  <% if @user_posts.any? %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Title</th>
          <th>Content</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @user_posts.each do |post| %>
          <tr>
            <td><%= post.title %></td>
            <td><%= truncate(post.content, length: 50) %></td>
            <td class="d-flex">
              <%= link_to 'Show', post_path(post), class: "btn btn-primary btn-sm" %>
              <%= link_to 'Edit', edit_post_path(post), class: "btn btn-secondary btn-sm" %>
              <%= button_to 'Delete', post_path(post), method: :delete, class: "btn btn-danger btn-sm" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>You have no posts.</p>
  <% end %>
</div>